### ISSUE TITLE
Unhandled error running shared-configs commands

### ISSUE THREAD

**Issue by andyt10** [renderedtext/cli#135]
Attempting to list (or add) a shared config via cli results in error:

```
SemaphoreClient::Exceptions::NotFound: Not found

Backtrace: 
/Library/Ruby/Gems/2.0.0/gems/semaphore_client-2.8.1/lib/semaphore_client/http_client.rb:12:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
/Library/Ruby/Gems/2.0.0/gems/semaphore_client-2.8.1/lib/semaphore_client/http_client.rb:7:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/request/encode_json.rb:24:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
/Library/Ruby/Gems/2.0.0/gems/semaphore_client-2.8.1/lib/semaphore_client/http_client.rb:55:in `public_send'
/Library/Ruby/Gems/2.0.0/gems/semaphore_client-2.8.1/lib/semaphore_client/http_client.rb:55:in `api_call'
/Library/Ruby/Gems/2.0.0/gems/semaphore_client-2.8.1/lib/semaphore_client/http_client.rb:37:in `get'
/Library/Ruby/Gems/2.0.0/gems/semaphore_client-2.8.1/lib/semaphore_client/api/shared_config.rb:17:in `list_for_org!'
/Library/Ruby/Gems/2.0.0/gems/sem-0.7.0/lib/sem/api/org.rb:27:in `shared_configs'
/Library/Ruby/Gems/2.0.0/gems/pmap-1.1.1/lib/pmap.rb:82:in `call'
/Library/Ruby/Gems/2.0.0/gems/pmap-1.1.1/lib/pmap.rb:82:in `block (2 levels) in pmap'
/Library/Ruby/Gems/2.0.0/gems/pmap-1.1.1/lib/pmap/thread_pool.rb:58:in `call'
/Library/Ruby/Gems/2.0.0/gems/pmap-1.1.1/lib/pmap/thread_pool.rb:58:in `block in spawn_worker'

Please report this issue by opening an issue on GitHub: https://github.com/renderedtext/cli/issues/new.

```
Doesn't seem to occur with team/project commands. :) 

First time I've used cli.

**Comment by andyt10** [comment]
Just read the docs and found the 'trace' command, here it is for list:

```
I, [2017-11-15T14:57:56.732457 #24713]  INFO -- : get https://api.semaphoreci.com/v2/orgs
I, [2017-11-15T14:57:57.779378 #24713]  INFO -- Status: 200
D, [2017-11-15T14:57:57.779469 #24713] DEBUG -- response: [{"id":"XXXXXXXX-d5e9-42c2-b2c3-503dbe2931d6","name":"ORG_NAME","username":"ORG_NAME","url":"https://api.semaphoreci.com/v2/orgs/ORG_NAME","projects_url":"https://api.semaphoreci.com/v2/orgs/ORG_NAME/projects","users_url":"https://api.semaphoreci.com/v2/orgs/ORG_NAME/users","teams_url":"https://api.semaphoreci.com/v2/orgs/ORG_NAME/teams","secrets_url":"https://api.semaphoreci.com/v2/orgs/ORG_NAME/secrets","created_at":"2016-11-07T00:27:59Z","updated_at":"2017-11-15T03:37:53Z"}]
I, [2017-11-15T14:57:57.780657 #24713]  INFO -- : get https://api.semaphoreci.com/v2/orgs/ORG_NAME/shared_configs
I, [2017-11-15T14:57:58.904553 #24713]  INFO -- Status: 404
D, [2017-11-15T14:57:58.904645 #24713] DEBUG -- response: {"message":"Not found","documentation_url":"http://semaphoreci.com/docs/api-v2-overview.html"}
[PANIC] Unhandled error.
...same as above....
```
I also just noticed that there's a PR in for renaming 'shared config' to 'secret', and that API v2 seems to have secret and not shared config. I assume this is all related?  😄

**Comment by nemus993** [comment]
Sorry for the inconvenience @andyt10 and thanks for reaching out, 
we are happy to see our Api and CLI are being used. 😄 
Unfortunately,  we are still in prototype phase and this mean that we are still doing bunch of breaking changes and improvements.
Nevertheless, we are working hard to get our Api and CLI published and in full stable mode.
Thanks again for your patience

**Comment by andyt10** [comment]
@nemus993 No worries! 
I didn't actually realise the cli was alpha until after I'd had a play.

We're super keen to start doing more with your v2 API and are excited to see what you're developing. 

Automating the creation of Semaphore projects is high on our list of things to improve our workflow. It suits our microservices architecture. 

Waiting as patiently as possible. 😄
